mod "boxen", "3.6.1",
	:github_tarball => "boxen/puppet-boxen"

mod "homebrew", "2.0.0",
	:github_tarball => "boxen/puppet-homebrew"

mod "stdlib", "4.0.0",
	:github_tarball => "puppetlabs/puppetlabs-stdlib"
